import React, { useEffect, useState } from 'react';
import type { PipelineStage } from '../hooks/useSSE';
import { useTypewriter, useGradualReveal } from '../hooks/useTypewriter';

interface ThinkingTrailProps {
  stages: PipelineStage[];
  // True while the assistant is still streaming this message
  streaming: boolean;
  // Time the user sent the message (for total elapsed display)
  startedAt: number;
}

const STAGE_LABELS: Record<string, string> = {
  intent: 'Classifying intent',
  retrieval_vector: 'Vector search',
  retrieval_bm25: 'BM25 search',
  retrieval_graph: 'Graph search',
  // Lucene full-text over section_title only. It is a LEXICAL branch that runs
  // inside the KG modes, so it must be visible: a KG answer whose only source is
  // this branch is not a graph answer, and the trail is where a reader sees that.
  retrieval_title: 'Title search (lexical)',
  retrieval_hop: 'Reference-chain hop',
  retrieval_adaptive: 'Adaptive search · summary',
  hop_research_done: 'Research planning · done',
  hop_finish: 'Adaptive search · stop',
  hop_warning: 'Adaptive search · warning',
  rerank: 'Reranking results',
  answer: 'Generating answer',
  sources: 'Collecting sources',
  error: 'Error',
};

// Per-tool labels for hop_act steps (main retrieval loop) and the research
// planning sub-loop. Each iter renders as a separate step in the trail.
const HOP_TOOL_LABELS: Record<string, string> = {
  // Main retrieval loop
  cypher_query: 'Adaptive · cypher_query',
  expand_term: 'Adaptive · expand_term',
  vector_search: 'Adaptive · vector_search',
  inspect_chunk: 'Adaptive · inspect_chunk',
  // Research-planning loop (KG inspection before retrieval)
  kg_search_titles: 'Research · kg_search_titles',
  kg_search_terms: 'Research · kg_search_terms',
  kg_search_specs: 'Research · kg_search_specs',
  finish: 'Research · finish (gaps)',
};

// Stages that we render as discrete steps (token-level "answer" events are folded
// into a single synthesized step; "answer_start" is consumed as input metadata only).
// Research-loop and main-loop iter events are handled explicitly with stream
// accumulation, NOT via this set.
const NON_TOKEN_VISIBLE = new Set([
  'intent',
  'retrieval_vector',
  'retrieval_bm25',
  'retrieval_graph',
  'retrieval_hop',
  'retrieval_adaptive',
  'hop_research_done',
  'hop_finish',
  'hop_warning',
  'rerank',
  'sources',
  'error',
]);

interface PreviewChunk {
  spec_id: string;
  section: string;
  score?: number;
  preview?: string;
}

interface RetrievalData {
  count?: number;
  seeds?: string[];
  top?: PreviewChunk[];
  input?: unknown;
  output?: unknown;
}

interface DisplayStep {
  kind: string;
  label: string;
  startTs: number;
  endTs: number;
  // Raw payload from the SSE event (used for input/output expansion)
  data?: unknown;
  // For the synthesized "answer" step: the prompt sent to the LLM
  answerInput?: unknown;
  // For the synthesized "answer" step: the streamed text accumulated so far
  answerOutput?: string;
  // For the synthesized "answer" step: thinking trace (reasoning models)
  answerThinking?: string;
  // For the graph step: live-streamed Cypher being generated by the LLM
  cypherStreaming?: string;
  // For the graph step: live-streamed thinking trace (reasoning models, before Cypher)
  cypherThinking?: string;
  // True while we're still receiving cypher tokens (graph_start fired, retrieval_graph hasn't yet)
  cypherInProgress?: boolean;
  // Adaptive hop step (one per iter): the planner's reasoning + decision JSON.
  // Reused by both the main retrieval loop AND the research-planning sub-loop.
  hopThinking?: string;
  hopPlannerRaw?: string;
  hopDecision?: { thought?: string; tool?: string; args?: unknown; remaining_gaps?: string[] };
  // True while planner tokens are still streaming (no hop_act yet)
  hopInProgress?: boolean;
  // Iteration number this step represents
  hopIter?: number;
}

function summarize(stage: string, data: unknown): string {
  if (!data || typeof data !== 'object') return '';
  const d = data as Record<string, unknown>;

  if (stage === 'intent') {
    const intent = d.intent as string | undefined;
    const terms = d.terms as { primary_term?: string; network_functions?: string[] } | undefined;
    const parts: string[] = [];
    if (intent) parts.push(intent);
    if (terms?.primary_term) parts.push(`term: ${terms.primary_term}`);
    if (terms?.network_functions?.length) parts.push(`NFs: ${terms.network_functions.join(', ')}`);
    return parts.join(' · ');
  }
  if (stage.startsWith('retrieval_') || stage === 'rerank') {
    const r = d as RetrievalData;
    const bits: string[] = [];
    if (typeof r.count === 'number') bits.push(`${r.count} chunks`);
    if (r.seeds?.length) bits.push(`seeds: ${r.seeds.join(', ')}`);
    return bits.join(' · ');
  }
  if (stage === 'sources') {
    return Array.isArray(d) ? `${(d as unknown[]).length} sources` : '';
  }
  if (stage === 'hop_research_done') {
    const gaps = (d.output as { gaps?: string[] } | undefined)?.gaps ?? (d.gaps as string[] | undefined);
    const iters = (d.output as { iters?: number } | undefined)?.iters;
    const finish = (d.output as { finish_emitted?: boolean } | undefined)?.finish_emitted;
    const bits: string[] = [];
    if (gaps?.length) bits.push(`${gaps.length} gap${gaps.length === 1 ? '' : 's'}`);
    if (typeof iters === 'number') bits.push(`${iters} kg query${iters === 1 ? '' : 's'}`);
    if (finish === false) bits.push('no finish');
    return bits.join(' · ');
  }
  if (stage === 'hop_research_act') {
    const iter = d.iter as number | undefined;
    const tool = d.tool as string | undefined;
    const out = d.output as Record<string, unknown> | undefined;
    const count = (typeof d.count === 'number' ? d.count : (out?.count as number | undefined));
    const gapCount = (out?.gaps as unknown[] | undefined)?.length;
    const bits: string[] = [];
    if (typeof iter === 'number') bits.push(`iter ${iter}`);
    if (tool) bits.push(tool);
    if (tool === 'finish' && typeof gapCount === 'number') {
      bits.push(`${gapCount} gap${gapCount === 1 ? '' : 's'}`);
    } else if (typeof count === 'number') {
      bits.push(`${count} result${count === 1 ? '' : 's'}`);
    }
    return bits.join(' · ');
  }
  if (stage === 'hop_finish') {
    const iters = d.iters as number | undefined;
    const total = d.total_chunks as number | undefined;
    const reason = d.reason as string | undefined;
    const elapsed = d.elapsed_ms as number | undefined;
    const bits: string[] = [];
    if (typeof iters === 'number') bits.push(`${iters} iter${iters === 1 ? '' : 's'}`);
    if (typeof total === 'number') bits.push(`${total} new chunks`);
    if (reason) bits.push(reason);
    if (typeof elapsed === 'number') bits.push(`${elapsed}ms`);
    return bits.join(' · ');
  }
  if (stage === 'hop_act') {
    const iter = d.iter as number | undefined;
    const tool = d.tool as string | undefined;
    const out = d.output as Record<string, unknown> | undefined;
    const added = (typeof d.added === 'number' ? d.added : (out?.added as number | undefined));
    const bits: string[] = [];
    if (typeof iter === 'number') bits.push(`iter ${iter}`);
    if (tool) bits.push(tool);
    if (typeof out?.rows === 'number') bits.push(`rows: ${out.rows}`);
    if (typeof added === 'number') bits.push(`added: ${added}`);
    if (out?.error) bits.push(`error`);
    return bits.join(' · ');
  }
  if (stage === 'hop_warning') {
    const phase = d.phase as string | undefined;
    const err = d.error as string | undefined;
    return [phase, err].filter(Boolean).join(' · ');
  }
  return '';
}

function useTick(active: boolean): number {
  const [, setTick] = useState(0);
  useEffect(() => {
    if (!active) return;
    const id = setInterval(() => setTick((t) => t + 1), 200);
    return () => clearInterval(id);
  }, [active]);
  return Date.now();
}

function fmtDuration(ms: number): string {
  if (ms < 1000) return `${Math.max(0, Math.round(ms))}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function ChunkPreviewList({ items }: { items: PreviewChunk[] }) {
  if (!items.length) return null;
  return (
    <ul className="mt-1.5 space-y-1 text-xs text-gray-500 animate-fade-in">
      {items.map((c, i) => (
        <li key={i} className="leading-snug">
          <span className="font-medium text-gray-700">
            {c.spec_id}{c.section ? ` §${c.section}` : ''}
          </span>
          {typeof c.score === 'number' && (
            <span className="ml-1 text-gray-400">({c.score.toFixed(2)})</span>
          )}
          {c.preview && <span className="block text-gray-500">{c.preview}</span>}
        </li>
      ))}
    </ul>
  );
}

// Reveal LLM prompt char-by-char on mount — long multi-line text feels less
// abrupt this way; matches the streaming aesthetic of the rest of the trail.
// Shows the FULL prompt sent to the model, including all injected context
// (schema, resolved terms, retrieved chunks, intent template) — i.e. exactly
// what the model saw.
function PromptPanel({ text }: { text: string }) {
  // No gradual reveal here. The hook exists for token streams, where text arrives over
  // time; a prompt is already complete when the panel opens, and animating 25 KB of it
  // leaves the reader watching the static schema scroll past while the part they opened
  // the panel for — the dynamic block at the END, carrying the intent, resolved terms
  // and the question itself — has not appeared yet. Worse, the char count beside the
  // heading shows the FULL length, so a half-revealed panel reads as a truncated prompt.
  const displayed = text;
  return (
    <div>
      <div className="text-[11px] uppercase tracking-wide text-gray-500 mb-1">
        Input prompt
        <span className="ml-2 normal-case text-gray-400 text-[10px]">
          {text.length.toLocaleString()} chars
        </span>
        {/* A stored run keeps only the prompt's TAIL (run_bench PROMPT_KEEP_CHARS), so
            the count above is what survived, not what was sent. Without saying so the
            panel reads as a complete prompt that inexplicably lacks a question. */}
        {text.startsWith('…[head elided]…') && (
          <span className="ml-2 normal-case text-amber-600 text-[10px]">
            tail only — the schema and pattern menu above it were dropped when the run
            was stored
          </span>
        )}
      </div>
      <pre className="text-[12px] leading-relaxed whitespace-pre-wrap break-words text-gray-700 bg-white border border-gray-200 rounded p-2 max-h-96 overflow-auto font-mono">
        {displayed}
      </pre>
    </div>
  );
}

// Final Cypher (after token streaming finishes) — gradually reveal so it
// doesn't pop in instantly when the user expands the step.
function CypherPanel({ text }: { text: string }) {
  const displayed = useGradualReveal(text, 8);
  return (
    <div>
      <div className="text-[11px] uppercase tracking-wide text-gray-500 mb-1">
        Response (Cypher)
      </div>
      <pre className="text-[12px] leading-relaxed whitespace-pre-wrap break-words text-gray-700 bg-white border border-gray-200 rounded p-2 max-h-60 overflow-auto font-mono">
        {displayed}
      </pre>
    </div>
  );
}

// Pretty-print a JSON-y value into a small monospace block; truncate huge strings to keep the UI light
function PrettyJson({ value }: { value: unknown }) {
  let text: string;
  try {
    text = typeof value === 'string' ? value : JSON.stringify(value, null, 2);
  } catch {
    text = String(value);
  }
  // Reveal gradually instead of popping the whole JSON block at once
  const displayed = useGradualReveal(text);
  return (
    <pre className="text-[11.5px] leading-snug whitespace-pre-wrap break-words text-gray-700 bg-white border border-gray-200 rounded p-2 max-h-60 overflow-auto font-mono">
      {displayed}
    </pre>
  );
}

// Build the display step list from raw SSE stages.
// - Folds `answer` token events into a single synthesized "Generating answer" step
// - Pulls the prompt from the `answer_start` marker as that step's input
function buildSteps(stages: PipelineStage[], streaming: boolean, now: number): DisplayStep[] {
  const out: DisplayStep[] = [];
  let answerStart: number | null = null;
  let answerLast: number | null = null;
  let answerInput: unknown = undefined;
  let answerBuffer = '';
  let answerThinkingBuffer = '';

  // In-progress graph step (between graph_start and retrieval_graph): we accumulate
  // cypher tokens and show it live so the user sees the LLM writing the query.
  let graphStartTs: number | null = null;
  let graphInput: unknown = undefined;
  let graphCypherSoFar = '';
  let graphThinkingSoFar = '';

  // Adaptive hop iter accumulator. We start fresh at every `hop_plan` and emit
  // a step at `hop_act` (or close it at end-of-stream if streaming).
  let hopIter: number | null = null;
  let hopStartTs: number | null = null;
  let hopThinkingSoFar = '';
  let hopPlannerRawSoFar = '';
  let hopDecision: DisplayStep['hopDecision'] | undefined;

  // Research-planning iter accumulator: one block per `hop_research_iter_start`,
  // closed by the matching `hop_research_act`. Each iter renders as its own step
  // (label = the tool the LLM picked, e.g. "Research · kg_search_titles").
  let researchIter: number | null = null;
  let researchStartTs: number | null = null;
  let researchThinkingSoFar = '';
  let researchTokenSoFar = '';
  let researchDecision: DisplayStep['hopDecision'] | undefined;

  const flushAnswer = (closingTs: number | null) => {
    if (answerStart === null && answerInput === undefined) return;
    const start = answerStart ?? closingTs ?? Date.now();
    const end = closingTs ?? answerLast ?? start;
    out.push({
      kind: 'answer',
      label: STAGE_LABELS.answer,
      startTs: start,
      endTs: end,
      answerInput,
      answerOutput: answerBuffer,
      answerThinking: answerThinkingBuffer,
    });
    answerStart = null;
    answerLast = null;
    answerInput = undefined;
    answerBuffer = '';
    answerThinkingBuffer = '';
  };

  for (const s of stages) {
    if (s.stage === 'answer_start') {
      answerInput = (s.data as { input?: unknown } | undefined)?.input ?? s.data;
      if (answerStart === null) answerStart = s.timestamp;
      continue;
    }
    if (s.stage === 'thinking') {
      // Thinking arrives BEFORE the first answer token for reasoning models;
      // anchor the answer step at the first thinking event so its duration spans the
      // full reasoning + generation phase.
      if (answerStart === null) answerStart = s.timestamp;
      answerLast = s.timestamp;
      const tok = s.data as string | undefined;
      if (tok) answerThinkingBuffer += tok;
      continue;
    }
    if (s.stage === 'answer') {
      if (answerStart === null) answerStart = s.timestamp;
      answerLast = s.timestamp;
      const tok = s.data as string | undefined;
      if (tok) answerBuffer += tok;
      continue;
    }
    // ----- graph step streaming -----
    if (s.stage === 'graph_start') {
      graphStartTs = s.timestamp;
      graphInput = (s.data as { input?: unknown } | undefined)?.input;
      graphCypherSoFar = '';
      graphThinkingSoFar = '';
      continue;
    }
    if (s.stage === 'graph_cypher_thinking') {
      const d = s.data as { token?: string; accumulated?: string } | undefined;
      if (d?.accumulated !== undefined) {
        graphThinkingSoFar = d.accumulated;
      } else if (d?.token) {
        graphThinkingSoFar += d.token;
      }
      continue;
    }
    if (s.stage === 'graph_cypher_token') {
      const d = s.data as { token?: string; accumulated?: string } | undefined;
      if (d?.accumulated !== undefined) {
        graphCypherSoFar = d.accumulated;
      } else if (d?.token) {
        graphCypherSoFar += d.token;
      }
      continue;
    }
    if (s.stage === 'retrieval_graph') {
      // Final graph event — push as a completed step using the accumulated state.
      // We carry the thinking buffer forward so users can still inspect it after the step ends.
      out.push({
        kind: 'retrieval_graph',
        label: STAGE_LABELS.retrieval_graph,
        startTs: graphStartTs ?? s.timestamp,
        endTs: s.timestamp,
        data: s.data,
        cypherThinking: graphThinkingSoFar || undefined,
        cypherInProgress: false,
      });
      graphStartTs = null;
      graphInput = undefined;
      graphCypherSoFar = '';
      graphThinkingSoFar = '';
      continue;
    }
    // ----- end graph -----

    // ----- research-planning sub-loop streaming -----
    // The planner LLM calls KG inspection tools (kg_search_titles, etc.) in a
    // small ReAct loop before emitting the final gap list via `finish`. Each
    // iter of this loop is rendered as one step (label = tool name).
    if (s.stage === 'hop_research_start') {
      // Start-of-phase marker — no step rendered, we just zero the accumulator.
      researchIter = null;
      researchStartTs = null;
      researchThinkingSoFar = '';
      researchTokenSoFar = '';
      researchDecision = undefined;
      continue;
    }
    if (s.stage === 'hop_research_iter_start') {
      const d = s.data as { iter?: number } | undefined;
      researchIter = d?.iter ?? null;
      researchStartTs = s.timestamp;
      researchThinkingSoFar = '';
      researchTokenSoFar = '';
      researchDecision = undefined;
      continue;
    }
    if (s.stage === 'hop_research_thinking') {
      const d = s.data as { token?: string; accumulated?: string } | undefined;
      if (d?.accumulated !== undefined) {
        researchThinkingSoFar = d.accumulated;
      } else if (d?.token) {
        researchThinkingSoFar += d.token;
      }
      continue;
    }
    if (s.stage === 'hop_research_token') {
      const d = s.data as { token?: string; accumulated?: string } | undefined;
      if (d?.accumulated !== undefined) {
        researchTokenSoFar = d.accumulated;
      } else if (d?.token) {
        researchTokenSoFar += d.token;
      }
      continue;
    }
    if (s.stage === 'hop_research_decision') {
      const d = s.data as DisplayStep['hopDecision'] | undefined;
      researchDecision = d;
      continue;
    }
    if (s.stage === 'hop_research_act') {
      const d = s.data as { iter?: number; tool?: string } | undefined;
      const toolLabel = (d?.tool && HOP_TOOL_LABELS[d.tool]) || `Research iter ${d?.iter ?? researchIter ?? '?'}`;
      out.push({
        kind: 'hop_research_act',
        label: toolLabel,
        startTs: researchStartTs ?? s.timestamp,
        endTs: s.timestamp,
        data: s.data,
        // Reuse hop* fields so the existing expanded panel renders identically.
        hopThinking: researchThinkingSoFar || undefined,
        hopPlannerRaw: researchTokenSoFar || undefined,
        hopDecision: researchDecision,
        hopIter: d?.iter ?? researchIter ?? undefined,
      });
      researchIter = null;
      researchStartTs = null;
      researchThinkingSoFar = '';
      researchTokenSoFar = '';
      researchDecision = undefined;
      continue;
    }
    // ----- end research planning -----

    // ----- adaptive hop iter streaming -----
    if (s.stage === 'hop_plan') {
      const d = s.data as { iter?: number } | undefined;
      hopIter = d?.iter ?? null;
      hopStartTs = s.timestamp;
      hopThinkingSoFar = '';
      hopPlannerRawSoFar = '';
      hopDecision = undefined;
      continue;
    }
    if (s.stage === 'hop_thinking') {
      const tok = (s.data as { token?: string } | undefined)?.token;
      if (tok) hopThinkingSoFar += tok;
      continue;
    }
    if (s.stage === 'hop_planner_token') {
      const tok = (s.data as { token?: string } | undefined)?.token;
      if (tok) hopPlannerRawSoFar += tok;
      continue;
    }
    if (s.stage === 'hop_decision') {
      const d = s.data as DisplayStep['hopDecision'] & { iter?: number } | undefined;
      hopDecision = d;
      continue;
    }
    if (s.stage === 'hop_act') {
      const d = s.data as { iter?: number; tool?: string } | undefined;
      const toolLabel = (d?.tool && HOP_TOOL_LABELS[d.tool]) || `Adaptive iter ${d?.iter ?? hopIter ?? '?'}`;
      out.push({
        kind: 'hop_act',
        label: toolLabel,
        startTs: hopStartTs ?? s.timestamp,
        endTs: s.timestamp,
        data: s.data,
        hopThinking: hopThinkingSoFar || undefined,
        hopPlannerRaw: hopPlannerRawSoFar || undefined,
        hopDecision,
        hopIter: d?.iter ?? hopIter ?? undefined,
      });
      // Reset for next iter.
      hopIter = null;
      hopStartTs = null;
      hopThinkingSoFar = '';
      hopPlannerRawSoFar = '';
      hopDecision = undefined;
      continue;
    }
    // ----- end adaptive hop -----

    if (s.stage === 'sources') {
      flushAnswer(s.timestamp);
    }
    if (NON_TOKEN_VISIBLE.has(s.stage)) {
      out.push({
        kind: s.stage,
        label: STAGE_LABELS[s.stage] ?? s.stage,
        startTs: s.timestamp,
        endTs: s.timestamp,
        data: s.data,
      });
    }
  }

  // If a research-planning iter is still in progress (iter_start fired but no
  // matching hop_research_act yet), emit a live step showing tokens flowing.
  if (researchStartTs !== null) {
    out.push({
      kind: 'hop_research_act',
      label: `Research iter ${researchIter ?? '?'}`,
      startTs: researchStartTs,
      endTs: streaming ? now : researchStartTs,
      data: { input: undefined },
      hopThinking: researchThinkingSoFar || undefined,
      hopPlannerRaw: researchTokenSoFar || undefined,
      hopDecision: researchDecision,
      hopIter: researchIter ?? undefined,
      hopInProgress: true,
    });
  }

  // If graph is still in progress (graph_start arrived but retrieval_graph hasn't),
  // show a live step with the cypher being typed (and any thinking that came before)
  if (graphStartTs !== null) {
    out.push({
      kind: 'retrieval_graph',
      label: STAGE_LABELS.retrieval_graph,
      startTs: graphStartTs,
      endTs: streaming ? now : graphStartTs,
      data: { input: graphInput },
      cypherStreaming: graphCypherSoFar,
      cypherThinking: graphThinkingSoFar || undefined,
      cypherInProgress: true,
    });
  }

  // Streaming may end mid-answer (no sources yet)
  if (answerStart !== null || answerInput !== undefined) {
    out.push({
      kind: 'answer',
      label: STAGE_LABELS.answer,
      startTs: answerStart ?? now,
      endTs: streaming ? now : (answerLast ?? answerStart ?? now),
      answerInput,
      answerOutput: answerBuffer,
      answerThinking: answerThinkingBuffer,
    });
  }
  return out;
}

// Compute per-step input/output for the expand panel
function getInputOutput(step: DisplayStep): { input: unknown; output: unknown } {
  if (step.kind === 'answer') {
    return { input: step.answerInput, output: step.answerOutput };
  }
  if (step.kind === 'sources') {
    // Sources data is a flat array — no separate input
    return { input: undefined, output: step.data };
  }
  const d = step.data as { input?: unknown; output?: unknown } | undefined;
  // The payload has an explicit input/output shape — honour it. Do NOT fall back to
  // `output ?? step.data`: step.data still carries the `input` field, which would make
  // the Output panel show the whole payload again (looking just like Input).
  if (d && typeof d === 'object' && ('input' in d || 'output' in d)) {
    return { input: d.input, output: d.output };
  }
  // Older-shape payloads: no explicit input/output split
  return { input: undefined, output: step.data };
}

function StepRow({
  step,
  index,
  prevEndTs,
  isRunning,
  now,
}: {
  step: DisplayStep;
  index: number;
  prevEndTs: number | null;
  isRunning: boolean;
  now: number;
}) {
  // Auto-expand the graph step while its Cypher is being typed live
  const [expanded, setExpanded] = useState(step.cypherInProgress === true);

  // Per-step duration:
  //   - answer step: actual span (real LLM time)
  //   - graph step (in progress): live elapsed
  //   - other steps: gap from previous step's completion
  //   - first step: 0 (we don't anchor to startedAt — that conflates network/buffering)
  let dur: number;
  if (step.kind === 'answer') {
    dur = (isRunning ? now : step.endTs) - step.startTs;
  } else if (step.cypherInProgress) {
    dur = now - step.startTs;
  } else if (prevEndTs === null) {
    dur = 0;
  } else {
    dur = step.endTs - prevEndTs;
  }

  const summary = summarize(step.kind, step.data);
  const top = (step.data as RetrievalData | undefined)?.top;
  const { input, output } = getInputOutput(step);
  // Pull the generated Cypher off the graph step's payload (sits at the top
  // level alongside input/output, since it's neither pure input nor pure output)
  const cypher =
    step.kind === 'retrieval_graph'
      ? (step.data as { cypher?: string } | undefined)?.cypher
      : undefined;
  // Full LLM prompt — for both graph and answer steps. Includes ALL injected
  // context (schema, resolved terms, retrieved chunks, intent template, etc.)
  // so the user sees exactly what the model was given.
  const llmPrompt: string | undefined =
    step.kind === 'retrieval_graph'
      ? (step.data as { input?: { prompt?: string } } | undefined)?.input?.prompt
      : step.kind === 'answer'
      ? (step.answerInput as { prompt?: string } | undefined)?.prompt
      : undefined;
  // Strip the prompt out of the input metadata so we don't render it twice
  // (once as a big text block, again as a JSON field). Also drop schema for the
  // graph step — it's huge and already embedded in the prompt.
  const inputMeta: unknown = (() => {
    if (input === undefined || input === null) return undefined;
    if (typeof input !== 'object') return input;
    const rest: Record<string, unknown> = { ...(input as Record<string, unknown>) };
    delete rest.prompt;
    if (step.kind === 'retrieval_graph') delete rest.schema;
    return Object.keys(rest).length > 0 ? rest : undefined;
  })();
  // Smooth typewriter for a streaming Cypher (Ollama emits tokens in big bursts) and
  // for the answer expanded inside the trail (kept in sync with the main body)
  const cypherDisplay = useTypewriter(
    step.cypherStreaming || '',
    step.cypherInProgress === true,
  );
  const cypherThinkingDisplay = useTypewriter(
    step.cypherThinking || '',
    step.cypherInProgress === true,
  );
  const answerDisplay = useTypewriter(
    step.answerOutput || '',
    step.kind === 'answer' && isRunning,
  );
  const answerThinkingDisplay = useTypewriter(
    step.answerThinking || '',
    step.kind === 'answer' && isRunning,
  );
  const hasPrompt = !!(llmPrompt && llmPrompt.length > 0);
  const hasInputMeta = inputMeta !== undefined && inputMeta !== null && inputMeta !== '';
  const hasOutput = output !== undefined && output !== null && output !== '';
  const hasCypherThinking = !!(step.cypherThinking && step.cypherThinking.length > 0);
  const hasAnswerThinking = !!(step.answerThinking && step.answerThinking.length > 0);
  const hasHopThinking = !!(step.hopThinking && step.hopThinking.length > 0);
  const hasHopDecision = !!step.hopDecision;
  const canExpand =
    hasPrompt || hasInputMeta || hasOutput || step.cypherInProgress || !!cypher
    || hasCypherThinking || hasAnswerThinking || hasHopThinking || hasHopDecision;

  return (
    <li className="relative text-sm animate-fade-in-up">
      <span
        className={`absolute -left-[21px] top-1.5 w-2 h-2 rounded-full ${
          step.kind === 'error'
            ? 'bg-red-500'
            : isRunning
            ? 'bg-blue-500 animate-pulse'
            : 'bg-gray-400'
        }`}
      />
      <div className="flex items-baseline gap-2">
        <span className="font-medium text-gray-700">{step.label}</span>
        <span className="text-xs text-gray-400 tabular-nums">
          {fmtDuration(Math.max(0, dur))}
        </span>
        {canExpand && (
          <button
            type="button"
            onClick={() => setExpanded((v) => !v)}
            className="ml-auto inline-flex items-center gap-1 text-[11px] text-gray-500
                       hover:text-gray-700 transition-colors"
          >
            <svg
              width="10"
              height="10"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              className={`transition-transform ${expanded ? 'rotate-90' : ''}`}
            >
              <path d="M9 18l6-6-6-6" />
            </svg>
            {expanded ? 'Hide' : 'Details'}
          </button>
        )}
      </div>
      {summary && <div className="text-xs text-gray-500 mt-0.5">{summary}</div>}
      {Array.isArray(top) && top.length > 0 && !expanded && <ChunkPreviewList items={top} />}

      {/* Inline previews while the step is running (so users see the LLM working
          without having to click Details): for graph step we prefer thinking when
          the Cypher hasn't started yet, then switch to Cypher once it does. */}
      {step.cypherInProgress && !expanded && (
        <pre className="mt-1.5 text-[11.5px] leading-snug whitespace-pre-wrap break-words text-gray-600 bg-gray-50 border border-gray-200 rounded p-2 max-h-32 overflow-auto font-mono">
          {cypherDisplay || cypherThinkingDisplay}
          <span className="inline-block w-1.5 h-3 bg-gray-500 animate-pulse align-text-bottom ml-0.5" />
        </pre>
      )}
      {/* For the answer step while thinking, show a brief thinking preview inline */}
      {step.kind === 'answer' && isRunning && !expanded && !answerDisplay && answerThinkingDisplay && (
        <pre className="mt-1.5 text-[11.5px] leading-snug whitespace-pre-wrap break-words text-gray-500 italic bg-gray-50 border border-gray-200 rounded p-2 max-h-32 overflow-auto">
          {answerThinkingDisplay}
          <span className="inline-block w-1.5 h-3 bg-gray-500 animate-pulse align-text-bottom ml-0.5" />
        </pre>
      )}

      {expanded && (
        <div className="mt-2 space-y-2 animate-fade-in">
          {/* ---------- 1. INPUT (full prompt sent to LLM, including injected context) ---------- */}
          {hasPrompt && <PromptPanel text={llmPrompt!} />}
          {/* Input metadata block intentionally hidden — user only wants the prompt visible */}
          {!hasPrompt && hasInputMeta && (
            <div>
              <div className="text-[11px] uppercase tracking-wide text-gray-500 mb-1">
                Input
              </div>
              <PrettyJson value={inputMeta} />
            </div>
          )}

          {/* ---------- 2. THINKING (reasoning trace, between Input and Response) ---------- */}
          {hasCypherThinking && (
            <div>
              <div className="text-[11px] uppercase tracking-wide text-gray-500 mb-1 flex items-center gap-1.5">
                LLM Thinking
                {step.cypherInProgress && !cypherDisplay && (
                  <span className="w-1.5 h-1.5 bg-amber-500 rounded-full animate-pulse" />
                )}
              </div>
              <pre className="text-[12px] leading-relaxed whitespace-pre-wrap break-words text-gray-600 italic bg-amber-50 border border-amber-200 rounded p-2 max-h-72 overflow-auto">
                {cypherThinkingDisplay}
                {step.cypherInProgress && !cypherDisplay && (
                  <span className="inline-block w-1.5 h-4 bg-gray-500 animate-pulse align-text-bottom ml-0.5" />
                )}
              </pre>
            </div>
          )}
          {hasHopThinking && (
            <div>
              <div className="text-[11px] uppercase tracking-wide text-gray-500 mb-1">
                Planner Thinking
              </div>
              <pre className="text-[12px] leading-relaxed whitespace-pre-wrap break-words text-gray-600 italic bg-amber-50 border border-amber-200 rounded p-2 max-h-72 overflow-auto">
                {step.hopThinking}
              </pre>
            </div>
          )}
          {hasHopDecision && (
            <div>
              <div className="text-[11px] uppercase tracking-wide text-gray-500 mb-1">
                Planner Decision
              </div>
              <PrettyJson value={step.hopDecision} />
            </div>
          )}
          {hasAnswerThinking && (
            <div>
              <div className="text-[11px] uppercase tracking-wide text-gray-500 mb-1 flex items-center gap-1.5">
                LLM Thinking
                {step.kind === 'answer' && isRunning && !answerDisplay && (
                  <span className="w-1.5 h-1.5 bg-amber-500 rounded-full animate-pulse" />
                )}
              </div>
              <pre className="text-[12px] leading-relaxed whitespace-pre-wrap break-words text-gray-600 italic bg-amber-50 border border-amber-200 rounded p-2 max-h-72 overflow-auto">
                {answerThinkingDisplay}
                {step.kind === 'answer' && isRunning && !answerDisplay && (
                  <span className="inline-block w-1.5 h-4 bg-gray-500 animate-pulse align-text-bottom ml-0.5" />
                )}
              </pre>
            </div>
          )}

          {/* ---------- 3. RESPONSE (LLM output: live Cypher, final Cypher, or answer text) ---------- */}
          {step.cypherInProgress && (
            <div>
              <div className="text-[11px] uppercase tracking-wide text-gray-500 mb-1 flex items-center gap-1.5">
                Response (Cypher)
                <span className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-pulse" />
              </div>
              <pre className="text-[12px] leading-relaxed whitespace-pre-wrap break-words text-gray-700 bg-white border border-gray-200 rounded p-2 max-h-72 overflow-auto font-mono">
                {cypherDisplay}
                <span className="inline-block w-1.5 h-4 bg-gray-500 animate-pulse align-text-bottom ml-0.5" />
              </pre>
            </div>
          )}
          {!step.cypherInProgress && cypher && <CypherPanel text={cypher} />}
          {hasOutput && (
            <div>
              <div className="text-[11px] uppercase tracking-wide text-gray-500 mb-1">
                {step.kind === 'answer' ? 'Response' : 'Output'}
              </div>
              {step.kind === 'answer' ? (
                <pre className="text-[12px] leading-relaxed whitespace-pre-wrap break-words text-gray-700 bg-white border border-gray-200 rounded p-2 max-h-72 overflow-auto">
                  {typeof output === 'string' ? answerDisplay : ''}
                  {isRunning && (
                    <span className="inline-block w-1.5 h-4 bg-gray-500 animate-pulse align-text-bottom ml-0.5" />
                  )}
                </pre>
              ) : (
                <PrettyJson value={output} />
              )}
            </div>
          )}
        </div>
      )}
    </li>
  );
}

export function ThinkingTrail({ stages, streaming, startedAt }: ThinkingTrailProps) {
  const [open, setOpen] = useState<boolean>(true);
  const userToggledRef = React.useRef(false);

  useEffect(() => {
    if (!userToggledRef.current) setOpen(streaming);
  }, [streaming]);

  const handleToggle = () => {
    userToggledRef.current = true;
    setOpen((v) => !v);
  };

  const now = useTick(streaming);
  const steps = buildSteps(stages, streaming, now);

  const lastTs = steps.length ? steps[steps.length - 1].endTs : startedAt;
  const totalElapsed = streaming ? now - startedAt : lastTs - startedAt;

  const headerLabel = streaming
    ? `Thinking… ${fmtDuration(totalElapsed)}`
    : `Thought for ${fmtDuration(totalElapsed)} · ${steps.length} step${steps.length === 1 ? '' : 's'}`;

  return (
    <div className="mb-3">
      <button
        type="button"
        onClick={handleToggle}
        className="inline-flex items-center gap-1.5 text-xs text-gray-500 hover:text-gray-700 transition-colors"
      >
        <svg
          width="12"
          height="12"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          className={`transition-transform ${open ? 'rotate-90' : ''}`}
        >
          <path d="M9 18l6-6-6-6" />
        </svg>
        <span>{headerLabel}</span>
      </button>

      {open && (
        <ol className="mt-2 ml-1 border-l border-gray-200 pl-4 space-y-2.5">
          {steps.map((step, i) => {
            const isLast = i === steps.length - 1;
            const isRunning = streaming && isLast;
            const prevEndTs = i === 0 ? null : steps[i - 1].endTs;
            return (
              <StepRow
                key={`${step.kind}-${i}`}
                step={step}
                index={i}
                prevEndTs={prevEndTs}
                isRunning={isRunning}
                now={now}
              />
            );
          })}
          {streaming && steps.length === 0 && (
            <li className="text-sm text-gray-400 italic">Starting…</li>
          )}
        </ol>
      )}
    </div>
  );
}
